AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello world lambda function
Resources:
  helloworldpython:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.6
      CodeUri: s3://ashwani-sam/e08466311ced2a4a15d3500f85cb6d96
      Description: Hello world lambda function
      MemorySize: 128
      Timeout: 3
      Events:
        HelloWorldSAMAPI:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
